RoutingAspNetCoreDemo.Conventional/Models/AccountVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RoutingAspNetCoreDemo.Conventional.Models
{
    public class AccountVM
    {
        public int ID { get; set; }
    }
}

RoutingAspNetCoreDemo.Conventional/Models/ErrorVM.cs
using System;

namespace RoutingAspNetCoreDemo.Conventional.Models
{
    public class ErrorVM
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RoutingAspNetCoreDemo.Conventional/Models/ParametersVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RoutingAspNetCoreDemo.Conventional.Models
{
    public class ParametersVM
    {
        public int Level { get; set; }
        public string Type { get; set; }
        public int ID { get; set; }
    }
}

RoutingAspNetCoreDemo.Conventional/Models/UserVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RoutingAspNetCoreDemo.Conventional.Models
{
    public class UserVM
    {
        public int ID { get; set; }
    }
}

RoutingAspNetCoreDemo.Conventional/Areas/Blog/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace RoutingAspNetCoreDemo.Conventional.Areas.Blog.Controllers
{
    [Area("blog")]
    public class PostController : Controller
    {
        public IActionResult Index(int id)
        {
            return View();
        }

        public IActionResult Article(string title)
        {
            return View();
        }
    }
}

RoutingAspNetCoreDemo.Conventional/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RoutingAspNetCoreDemo.Conventional.Models;

namespace RoutingAspNetCoreDemo.Conventional.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult Index(int id = 0)
        {
            AccountVM model = new AccountVM()
            {
                ID = id
            };
            return View(model);
        }

        //This action and the below action are distinct methods in C#,
        //because they accept different parameters.  However, the Routing
        //middleware will not be able to distinguish them using a URL,
        //so whenever we try to route to one of them we will get an AmbiguousActionException.
        public IActionResult IndexAmbiguous(int id = 0)
        {
            AccountVM model = new AccountVM()
            {
                ID = id
            };
            return View("Index", model);
        }

        public IActionResult IndexAmbiguous(string id = "0")
        {
            AccountVM model = new AccountVM()
            {
                ID = int.Parse(id)
            };
            return View("Index", model);
        }
    }
}

RoutingAspNetCoreDemo.Conventional/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RoutingAspNetCoreDemo.Conventional.Models;

namespace RoutingAspNetCoreDemo.Conventional.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Parameters(int level, string type, int id)
        {
            ParametersVM model = new ParametersVM()
            {
                Level = level,
                Type = type,
                ID = id
            };

            return View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorVM { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RoutingAspNetCoreDemo.Conventional/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RoutingAspNetCoreDemo.Conventional.Models;

namespace RoutingAspNetCoreDemo.Conventional.Controllers
{
    public class UserController : Controller
    {
        public IActionResult Index(int id = 0)
        {
            UserVM model = new UserVM()
            {
                ID = id
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Index(int id, UserVM model)
        {
            return RedirectToAction("Index");
        }
    }
}

RoutingAspNetCoreDemo.Conventional/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome Dear Reader!</h1>
</div>

<p>
    In this sample project, you will find many ways of setting up 
    Convention-based Routing for your ASP.NET Core MVC applications.
</p>

<p>
    The links above demonstrate some of these methods.  
    But before you look at them, take a look at the Startup.cs file in this project.
    In that file, you will see the routes defined in the call to UseEndpoints.
</p>

<p>For example, the "Home" link above demonstrates matching the "controller/action/id?" route pattern.</p>

<p>
    The "User (Mapped)" and "User (Route)" links above go to the same page, but via different routes;
    the former matches the basic "controller/action/id" route pattern, while the latter matches a specially-defined route.
</p>

<p>
    The "Ambiguous" link demonstrates what happens when the routing middleware cannot find a "best" route match;
    the system throws an AmbiguousActionException.
</p>

<p>The "Area" link shows how to link to Areas in our apps, and goes to the Blog area, Post controller, Index action.</p>

<p>Finally, the "Article" link shows how to use pattern matching in a route using the format /blog/post/article?title=Name</p>

<p>
    Thanks for reading, and Happy Coding!
</p>

RoutingAspNetCoreDemo.Conventional/Views/Home/Parameters.cshtml
@model RoutingAspNetCoreDemo.Conventional.Models.ParametersVM
@{
    ViewData["Title"] = "Parameters";
}

<h1>Parameters</h1>

<p>You passed in: Level @Model.Level, Type "@Model.Type", and ID @Model.ID.</p>

<p>
    Now try changing the parameters in the URL!
</p>

RoutingAspNetCoreDemo.Conventional/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RoutingAspNetCoreDemo.Conventional</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Conventional Routing Demo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-route="parameters"
                               asp-route-id="19"
                               asp-route-type="Test Name"
                               asp-route-level="5">Parameters</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-route="account" asp-route-id="5">Account</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="User" asp-action="Index" asp-route-id="89">User (Mapped)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-route="User" asp-route-id="89">User (Route)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="account" asp-action="IndexAmbiguous" asp-route-id="77">Ambiguous</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="blog" asp-controller="Post" asp-action="Index">Area</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="blog" asp-controller="Post" asp-action="Article" asp-route-title="this-is-a-test-article">Article</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>